import React,{useState,useEffect,Suspense}  from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/Home.module.scss'
import { getStoriesByCat } from '../../../services/stories'
import {
  FireOutlined,
  TabletOutlined
} from '@ant-design/icons';
import BlogHead from '../../../components/BlogHead'
import {ArticleHeader} from '../../../components/Header'
import {HomeMenu as Menu} from '../../../components/Menu'
import Loading from '../../../Loading'
import PlayerWidget from '../../../components/PlayerWidget'
import { useRouter } from 'next/router'
import Script from 'next/script'
import * as gtag from '../../../lib/gtag'
import Link from 'next/link'

export default function WebStories({category}) {

  const [articles,setArticles] =  useState([])
  const router = useRouter()
  const cat = category.charAt(0).toUpperCase()+category.substring(1)


  useEffect(()=>{
    (async ()=>{
      const res = await getStoriesByCat(cat)
      setArticles(res.data)
    })();
  },['init'])



  useEffect(() => {
    const handleRouteChange = (url) => {
      gtag.pageview(url)
    }
    router.events.on('routeChangeComplete', handleRouteChange)
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange)
    }
  }, [router.events])

  return (
    <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css?family=Inconsolata|Montserrat:400,500,600,700|Crimson+Text:400,600" rel="stylesheet"></link>
        </Head>
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${gtag.GA_TRACKING_ID}`}
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${gtag.GA_TRACKING_ID}', {
                page_path: window.location.pathname,
              });
            `,
          }}
        />
        <div className={styles.container}>
          <Menu/>
          <main className={styles.main}>
            <div className={styles.articles + " "+styles.mTop}>
              {/* <br></br>
              <input className={"searchInput"} type={"search"} placeholder='Search ...'/>
              <br></br> */}
              <h3 className={styles.h3}> <FireOutlined /> &nbsp;  Stories</h3>
              <div className={styles.articleList}>
                {articles && articles.length >0 ? articles?.map((article,index)=>{
                  return(
                    <div  
                        key={index}
                        className={styles.player}>
                        <PlayerWidget
                          title={"Consectetur aute non incididunt esse Lorem dolore mollit occaecat elit."}
                          img={article?.poster || "https://picsum.photos/360/370"}
                          logo={"https://picsum.photos/50/50"}
                          url={`/${category}/web-story/${article?._id}/${article?.slug}`}
                          category={article?.category}
                        />
                      </div>
                    
                  )
                }):(
                  <Loading/>
                )}
                </div>
            </div>
          </main>

          <footer className="ampstart-footer flex flex-column items-center px3">
            <nav className="ampstart-footer-nav">
                <ul className="list-reset flex flex-wrap mb3">
                  <li className="px1">
                      <a className="text-decoration-none ampstart-label" href="#">About</a>
                  </li>
                  <li className="px1">
                      <a className="text-decoration-none ampstart-label" href="#">Contact</a>
                  </li>
                  <li className="px1">
                      <a className="text-decoration-none ampstart-label" href="#">Terms</a>
                  </li>
                </ul>
            </nav>
            <small> © Your Company, 2016 </small>
          </footer>
        </div>
    </>
  )
}

export async function getServerSideProps(context) {
  // Fetch data from external API
  
  const { req, query, res, asPath, pathname } = context;
  const {category}  = query

  // Pass data to the page via props

  return { 
      props: {
        category : category
      } 
  }
}
