import React,{useState,useEffect}  from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import ArticlePreview from '../components/ArticlePreview'
import { getTopArticles } from '../services/articles'
import {HomeMenu as Menu} from '../components/Menu'
import StoriesWidget from '../components/StoriesWidget'
import { useRouter } from 'next/router'
import Script from 'next/script'
import * as gtag from '../lib/gtag'
import Pagination from '../components/Pagination'



export default function Home() {

  const [articles,setArticles] =  useState([])
  const [mainArticle,setMainArticle] =  useState([])
  const [articles1,setArticles1] =  useState([])
  const [articles2,setArticles2] =  useState([])
  const router = useRouter()


  useEffect(()=>{
    (async ()=>{
      const res = await getTopArticles()
      setArticles([...res?.data,...res?.data,...res?.data,...res?.data].splice(0,11))
    })();
  },['init'])

  useEffect(()=>{
    if(articles?.length > 0){
      const middleIndex = 4;
      const [main] = articles.splice(0, 1) ;
      const firstHalf = articles.splice(0, middleIndex);   
      const secondHalf = articles.splice(0,articles?.length);
      setMainArticle(main)
      setArticles1(firstHalf)
      setArticles2(secondHalf)
    }
  },[articles])


  useEffect(() => {
    const handleRouteChange = (url) => {
      gtag.pageview(url)
    }
    router.events.on('routeChangeComplete', handleRouteChange)
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange)
    }
  }, [router.events])


  return (
    <>
        <Head>
          <title>Discover AI / Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css?family=Inconsolata|Montserrat:400,500,600,700|Crimson+Text:400,600" rel="stylesheet"></link>
        </Head>
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${gtag.GA_TRACKING_ID}`}
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${gtag.GA_TRACKING_ID}', {
                page_path: window.location.pathname,
              });
            `,
          }}
        />
        <div className={ styles.containerLight }>
          <Menu/>
          <div className={styles.banner}>

          </div>
          <main className={styles.main}>

            <div className={styles.supportGrid}></div>
            <div className={styles.wrapper}>
              {mainArticle && (
                <div >
                  <ArticlePreview article={mainArticle} type={1}/>
                </div>
              )}
              <div className={styles.wrapper1Item}>
                {articles1?.map((article,index)=>{
                  return(
                    <div key={index} style={{minWidth:"200px"}} >
                      <ArticlePreview article={article} key={index} num={index} type={2}/>
                    </div>
                  )
                })}
              </div>
             
            </div>
            <StoriesWidget/>
            <div className={styles.wrapper2}>
              {articles2?.map((article,index)=>{
                return(
                  <div key={index}>
                   <ArticlePreview article={article} key={index} type={3}/>
                  </div>
                )
              })}
            </div>

            <Pagination
              url={"/article"}
              current={1}
              hasNext={true}
            />
          </main>

          <footer className="ampstart-footer flex flex-column items-center px3">
            <nav className="ampstart-footer-nav">
                <ul className="list-reset flex flex-wrap mb3">
                  <li className="px1">
                      <a className="text-decoration-none ampstart-label" href="#">About</a>
                  </li>
                  <li className="px1">
                      <a className="text-decoration-none ampstart-label" href="#">Contact</a>
                  </li>
                  <li className="px1">
                      <a className="text-decoration-none ampstart-label" href="#">Terms</a>
                  </li>
                </ul>
            </nav>
            <small> © Your Company, 2016 </small>
          </footer>
        </div>
    </>
  )
}